"""Every surface that names a strategy names the same set.

A strategy added to the code and missing from the reporter is a strategy whose
results nobody sees. One added to the frontend and missing from the registry is
a control that produces an error. Both have happened here: the 2026-09-03 audit
found the reporter dropping four strategies, which is H-02.

The catalog is the one list. These tests read every other surface and compare.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from kb_arena.strategies import STRATEGY_REGISTRY
from kb_arena.strategies.catalog import STRATEGY_CATALOG, default_strategy_names

ROOT = Path(__file__).resolve().parents[1]
CATALOG_NAMES = [spec.name for spec in STRATEGY_CATALOG]


def test_the_catalog_names_are_unique_and_ordered_deliberately():
    assert len(CATALOG_NAMES) == len(set(CATALOG_NAMES)), "a duplicate name hides one entry"
    assert (
        CATALOG_NAMES[0] == "naive_vector"
    ), "the first entry is the baseline a reader starts from"


def test_the_registry_holds_exactly_the_catalog():
    """A name in one and not the other is a strategy that half exists."""
    missing = sorted(set(CATALOG_NAMES) - set(STRATEGY_REGISTRY))
    extra = sorted(set(STRATEGY_REGISTRY) - set(CATALOG_NAMES))

    assert not missing, f"the catalog names these and the registry cannot build them: {missing}"
    assert not extra, f"the registry builds these and the catalog does not list them: {extra}"


def test_the_reporter_reads_every_catalog_strategy():
    """H-02: the reporter dropped bm25, rerank_vector, qiss and sqr."""
    from kb_arena.benchmark.reporter import STRATEGY_NAMES

    assert sorted(STRATEGY_NAMES) == sorted(CATALOG_NAMES)


def test_the_runner_offers_every_catalog_strategy_that_the_default_set_holds():
    from kb_arena.benchmark.runner import STRATEGY_NAMES

    assert sorted(STRATEGY_NAMES) == sorted(default_strategy_names())
    # The default set is a subset, and every member of it is a real strategy.
    assert set(default_strategy_names()) <= set(CATALOG_NAMES)


def test_the_default_set_leaves_out_only_what_needs_an_extra():
    """`sqr` needs the quantum extra, so `all` must not fail on a plain install."""
    left_out = sorted(set(CATALOG_NAMES) - set(default_strategy_names()))

    for name in left_out:
        spec = next(s for s in STRATEGY_CATALOG if s.name == name)
        assert (
            spec.experimental or spec.optional_extra
        ), f"{name} is not in the default set and the catalog gives no reason"


def _frontend_names() -> list[str]:
    source = (ROOT / "web" / "lib" / "api.ts").read_text()
    block = re.search(r"export const STRATEGIES = \[(.*?)\] as const;", source, re.S)
    assert block, "web/lib/api.ts must export a STRATEGIES list"
    return re.findall(r'"([a-z0-9_]+)"', block.group(1))


def test_the_frontend_lists_every_catalog_strategy():
    """A control the backend cannot build produces an error the user did not cause."""
    assert _frontend_names() == CATALOG_NAMES, (
        "web/lib/api.ts and the catalog disagree. The frontend list is generated by "
        "hand, so it drifts silently until somebody clicks the missing one."
    )


def test_the_frontend_labels_every_strategy_it_lists():
    source = (ROOT / "web" / "lib" / "api.ts").read_text()
    labels = re.search(r"STRATEGY_LABELS: Record<Strategy, string> = \{(.*?)\};", source, re.S)
    assert labels, "web/lib/api.ts must export STRATEGY_LABELS"
    labelled = re.findall(r"^\s*([a-z0-9_]+):", labels.group(1), re.M)

    assert sorted(labelled) == sorted(
        CATALOG_NAMES
    ), "a strategy with no label renders as a blank control"


def test_the_api_reports_every_catalog_strategy():
    """`GET /strategies` is what the frontend reads to know what is available."""
    from kb_arena.strategies.catalog import public_catalog

    payload = json.loads(json.dumps(public_catalog([]), default=list))
    assert [entry["name"] for entry in payload] == CATALOG_NAMES
    # Every entry says whether it is loaded, so a control can be disabled with
    # a reason rather than failing when a user clicks it.
    for entry in payload:
        assert entry["status"], f"{entry['name']} reports no runtime status"


def _readme_table() -> str:
    readme = (ROOT / "README.md").read_text()
    table = re.search(r"\| Strategy \| Architecture \|(.*?)\n\n", readme, re.S)
    assert table, "README.md must carry the strategy table"
    return table.group(1)


def test_the_readme_table_lists_every_catalog_strategy():
    """A strategy the code offers and the README omits is one nobody finds."""
    listed = set()
    for row in _readme_table().splitlines():
        if row.count("|") <= 3:
            continue
        cell = row.split("|")[1].strip()
        # The separator row is part of the table and names no strategy.
        if cell and set(cell) != {"-"}:
            listed.add(cell)
    labels = {spec.label for spec in STRATEGY_CATALOG}

    assert labels == listed, (
        f"the README omits {sorted(labels - listed)} and documents "
        f"{sorted(listed - labels)} that the catalog does not hold"
    )


def test_the_readme_marks_the_same_defaults_the_code_uses():
    """The Default column is a claim about what `--strategies all` runs."""
    marked: dict[str, bool] = {}
    for row in _readme_table().splitlines():
        cells = [c.strip() for c in row.split("|")]
        if len(cells) > 4 and cells[3] in {"Yes", "No"}:
            marked[cells[1]] = cells[3] == "Yes"
    assert marked, "the table must mark which strategies the default run covers"

    defaults = set(default_strategy_names())
    for spec in STRATEGY_CATALOG:
        if spec.label in marked:
            assert marked[spec.label] == (spec.name in defaults), (
                f"the README says {spec.label} default={marked[spec.label]}, and "
                f"`--strategies all` says {spec.name in defaults}"
            )


def test_the_frontend_fallback_marks_the_same_defaults_the_backend_runs():
    """The fallback is what the page shows before `GET /strategies` answers.

    It computed `default_benchmark: name !== "sqr"`, so rerank_vector read as a
    default when the backend excludes it. A rule drifts the moment a strategy
    leaves the default set for another reason, so the list is a list.
    """
    source = (ROOT / "web" / "lib" / "api.ts").read_text()
    block = re.search(
        r"DEFAULT_BENCHMARK_STRATEGIES: readonly Strategy\[\] = \[(.*?)\] as const;",
        source,
        re.S,
    )
    assert block, "web/lib/api.ts must export DEFAULT_BENCHMARK_STRATEGIES"
    listed = re.findall(r'"([a-z0-9_]+)"', block.group(1))

    assert sorted(listed) == sorted(
        default_strategy_names()
    ), "the frontend fallback and `--strategies all` disagree about the defaults"
    assert (
        "default_benchmark: DEFAULT_BENCHMARK_STRATEGIES.includes(name)" in source
    ), "the fallback record must read the list, not a rule about one name"


def test_the_benchmark_help_names_every_strategy():
    """The help listed seven of eleven, so `--help` denied four that exist."""
    from kb_arena import cli

    help_text = cli._strategy_option_help()
    for name in CATALOG_NAMES:
        assert name in help_text, f"`kb-arena benchmark --help` does not mention {name}"
    # It also says which ones `all` leaves out, so a user is not surprised.
    for name in set(CATALOG_NAMES) - set(default_strategy_names()):
        assert name in help_text.split("Not in 'all':")[-1]


def test_the_readme_prose_names_every_strategy_the_default_set_leaves_out():
    """The prose above the table said two different things, and both were wrong.

    One paragraph named four excluded strategies and the next named a different
    four. The table's Default column was right the whole time, and the test that
    read it passed. A reader reads the sentence first.

    The check reads one marked paragraph rather than everything above the table.
    A label that appears anywhere in the intro would otherwise satisfy a
    paragraph that never names it.
    """
    readme = (ROOT / "README.md").read_text()
    start = readme.index("<!-- default-set-exclusions -->")
    end = readme.index("<!-- /default-set-exclusions -->")
    paragraph = readme[start:end]

    for spec in STRATEGY_CATALOG:
        if spec.default_benchmark:
            assert (
                spec.label not in paragraph
            ), f"the README says {spec.label} is out of the default set, and the code runs it"
        else:
            assert (
                spec.label in paragraph
            ), f"the README does not say {spec.label} is out of the default set"
