#!/usr/bin/env python3
"""Write the reference docs from the code, so they cannot drift from it.

A hand-written command list goes stale the first time somebody adds a command
and forgets the doc. This session added three commands and four flags that no
document mentioned, which is the same failure the strategy table had.

Run this after changing a command, a flag, a route or a setting:

    python3 scripts/generate_reference.py

`tests/test_reference_is_current.py` runs it in memory and fails when the files
on disk differ, so a stale reference cannot merge.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Read the checkout this script lives in, not whatever `kb-arena` an editable
# install points at. Without this the script described a different working
# copy: run from `scripts/`, `sys.path` holds that directory and not the repo,
# so `import kb_arena` resolved through the installed package instead.
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

GENERATED = "<!-- Generated by scripts/generate_reference.py. Do not edit by hand. -->"


def _cli_commands() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Every command, its first help line, and its long flags."""
    import typer.models

    from kb_arena.cli import app

    rows: list[tuple[str, str, list[tuple[str, str]]]] = []
    for info in app.registered_commands:
        name = info.name or (info.callback.__name__ if info.callback else "")
        name = name.replace("_", "-")
        doc = (info.callback.__doc__ or "").strip() if info.callback else ""
        summary = doc.splitlines()[0] if doc else ""
        flags: list[tuple[str, str]] = []
        callback = info.callback
        if callback is not None:
            import inspect

            for param in inspect.signature(callback).parameters.values():
                default = param.default
                if not isinstance(default, typer.models.OptionInfo):
                    continue
                names = [d for d in (default.param_decls or []) if str(d).startswith("--")]
                flag = names[0] if names else f"--{param.name.replace('_', '-')}"
                flags.append((str(flag), (default.help or "").strip()))
        rows.append((name, summary, sorted(flags)))
    return sorted(rows)


def _api_routes() -> list[tuple[str, str, str]]:
    """Every route, its method, and whether it needs a token."""
    source = (ROOT / "kb_arena" / "chatbot" / "api.py").read_text()
    found: list[tuple[str, str, str]] = []
    for match in re.finditer(r'@app\.(get|post|put|delete)\(\s*"([^"]+)"([^)]*)\)', source, re.S):
        method, path, rest = match.group(1), match.group(2), match.group(3)
        if "require_read_auth" in rest:
            gate = "token, unless local or a published demo"
        elif "require_auth" in rest:
            gate = "token"
        else:
            gate = "open"
        found.append((path, method.upper(), gate))
    return sorted(found)


def _settings_fields() -> list[tuple[str, str, str]]:
    from kb_arena.settings import Settings

    rows = []
    for name, field in Settings.model_fields.items():
        default = field.default
        shown = "" if default is None else str(default)
        if isinstance(default, str) and default == "":
            shown = "(empty)"
        if "key" in name or "token" in name or "password" in name:
            shown = "(empty)" if not default else "(set)"
        rows.append((f"KB_ARENA_{name.upper()}", shown[:40], (field.description or "").strip()))
    return sorted(rows)


def render_cli() -> str:
    lines = [
        GENERATED,
        "",
        "# Command reference",
        "",
        "Every `kb-arena` command and its options.",
        "",
    ]
    for name, summary, flags in _cli_commands():
        lines += [f"## `kb-arena {name}`", ""]
        if summary:
            lines += [summary, ""]
        if flags:
            lines += ["| Option | What it does |", "|---|---|"]
            for flag, help_text in flags:
                lines.append(f"| `{flag}` | {help_text or '-'} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_api() -> str:
    lines = [
        GENERATED,
        "",
        "# HTTP reference",
        "",
        "Every route the server exposes, and what it asks of a caller.",
        "",
        "A route marked `token` needs `Authorization: Bearer <KB_ARENA_API_TOKEN>`.",
        "A route marked `token, unless local or a published demo` returns corpus",
        "content: it is open to a caller on this machine, open in a demo an",
        "operator published, and closed otherwise.",
        "",
        "| Route | Method | Auth |",
        "|---|---|---|",
    ]
    for path, method, gate in _api_routes():
        lines.append(f"| `{path}` | {method} | {gate} |")
    return "\n".join(lines).rstrip() + "\n"


def render_settings() -> str:
    lines = [
        GENERATED,
        "",
        "# Environment reference",
        "",
        "Every setting, read from `kb_arena/settings.py`. Each takes the",
        "`KB_ARENA_` prefix.",
        "",
        "| Variable | Default | What it does |",
        "|---|---|---|",
    ]
    for name, default, description in _settings_fields():
        lines.append(f"| `{name}` | `{default}` | {description or '-'} |")
    return "\n".join(lines).rstrip() + "\n"


TARGETS = {
    "docs/reference-cli.md": render_cli,
    "docs/reference-http.md": render_api,
    "docs/reference-environment.md": render_settings,
}


def main() -> int:
    for name, render in TARGETS.items():
        (ROOT / name).write_text(render())
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
