#!/usr/bin/env python3
"""Write the reference docs from the code, so they cannot drift from it.

A hand-written command list goes stale the first time somebody adds a command
and forgets the doc. This session added three commands and four flags that no
document mentioned, which is the same failure the strategy table had.

Run this after changing a command, a flag, a route or a setting:

    python3 scripts/generate_reference.py

`tests/test_reference_is_current.py` runs it in memory and fails when the files
on disk differ, so a stale reference cannot merge.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Read the checkout this script lives in, not whatever `kb-arena` an editable
# install points at. Without this the script described a different working
# copy: run from `scripts/`, `sys.path` holds that directory and not the repo,
# so `import kb_arena` resolved through the installed package instead.
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

GENERATED = "<!-- Generated by scripts/generate_reference.py. Do not edit by hand. -->"


def _cli_commands() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Every command, its first help line, and its long flags."""
    import typer.models

    from kb_arena.cli import app

    rows: list[tuple[str, str, list[tuple[str, str]]]] = []
    for info in app.registered_commands:
        name = info.name or (info.callback.__name__ if info.callback else "")
        name = name.replace("_", "-")
        doc = (info.callback.__doc__ or "").strip() if info.callback else ""
        summary = doc.splitlines()[0] if doc else ""
        flags: list[tuple[str, str]] = []
        callback = info.callback
        if callback is not None:
            import inspect

            for param in inspect.signature(callback).parameters.values():
                default = param.default
                if not isinstance(default, typer.models.OptionInfo):
                    continue
                names = [d for d in (default.param_decls or []) if str(d).startswith("--")]
                flag = names[0] if names else f"--{param.name.replace('_', '-')}"
                flags.append((str(flag), (default.help or "").strip()))
        rows.append((name, summary, sorted(flags)))
    return sorted(rows)


def _api_routes() -> list[tuple[str, str, str]]:
    """Every route the app serves, its method, and whether it needs a token.

    Read off the app, not off a regex over `api.py`. The app mounts a router
    with four routes under `/api/tools`, and a regex over one file missed every
    one of them. The reference then claimed to list every route and did not.
    """
    from kb_arena.chatbot.api import app
    from kb_arena.chatbot.auth import require_auth, require_read_auth

    # A set, not a list. A FastAPI version that copies a mounted router's
    # routes into `app.routes` as well as into the holder would otherwise print
    # every `/api/tools` row twice.
    found: set[tuple[str, str, str]] = set()
    for route in _walk_routes(app):
        path = getattr(route, "path", "")
        methods = getattr(route, "methods", None)
        dependant = getattr(route, "dependant", None)
        if not path or not methods or dependant is None:
            continue
        calls = {d.call for d in dependant.dependencies}
        if require_read_auth in calls:
            gate = "token, unless local or a published demo"
        elif require_auth in calls:
            gate = "token"
        else:
            gate = "open"
        for method in methods:
            if method in ("HEAD", "OPTIONS"):
                continue
            found.add((path, method.upper(), gate))

    # The app publishes its own route list. Checking the walk against it is what
    # makes a future mount impossible to miss in silence: a new router that this
    # walk does not reach fails the generator instead of shrinking the table.
    published = {
        (path, method.upper())
        for path, operations in app.openapi()["paths"].items()
        for method in operations
    }
    walked = {(path, method) for path, method, _ in found}
    missing = published - walked
    if missing:
        raise RuntimeError(
            f"the route walk missed {len(missing)} published route(s): {sorted(missing)}"
        )
    return sorted(found)


def _walk_routes(app):
    """Every route object, including the ones a mounted router holds.

    FastAPI wraps `include_router` in a lazy holder whose own `routes` list is
    empty until a request arrives. Following `original_router` reaches the real
    routes at generation time.
    """
    seen: list = []

    def _visit(holder) -> None:
        for route in getattr(holder, "routes", []) or []:
            if hasattr(route, "dependant"):
                seen.append(route)
            inner = getattr(route, "original_router", None)
            if inner is not None:
                _visit(inner)

    _visit(app)
    return seen


def _settings_fields() -> list[tuple[str, str, str]]:
    from kb_arena.settings import Settings

    rows = []
    for name, field in Settings.model_fields.items():
        default = field.default
        shown = "" if default is None else str(default)
        if isinstance(default, str) and default == "":
            shown = "(empty)"
        if "key" in name or "token" in name or "password" in name:
            shown = "(empty)" if not default else "(set)"
        rows.append((f"KB_ARENA_{name.upper()}", shown[:40], (field.description or "").strip()))
    return sorted(rows)


def _strategy_notes() -> dict[str, str]:
    """What each strategy does, keyed by `StrategySpec.name`.

    `STRATEGY_CATALOG` gives a name, a label, an architecture, and the flags
    that decide default-benchmark and API status. It carries no prose about
    what a strategy does or why it sits outside the default set, so that
    explanation lives here instead of in a hand-maintained doc.
    """
    return {
        "naive_vector": (
            "Chunks documents, embeds each chunk, and ranks by cosine similarity. Use "
            "it as the dense baseline."
        ),
        "contextual_vector": (
            "Adds parent headings and document context before embedding. Compare it "
            "with Naive Vector to measure whether local context resolves ambiguous "
            "terms."
        ),
        "qna_pairs": (
            "Generates likely questions and answers at index time, then retrieves "
            "those pairs. It can do well on recurring questions but may miss novel "
            "phrasing and has extra index-time cost."
        ),
        "knowledge_graph": (
            "Extracts entities and relationships into Neo4j and retrieves through "
            "graph query templates. It is most relevant when a question depends on "
            "explicit links across topics."
        ),
        "lightrag": (
            "Reads the same Neo4j graph as Knowledge Graph, through two paths at "
            "once. Local retrieval walks the one-hop neighborhood of entities matched "
            "in the question. Global retrieval groups fulltext-matched candidates "
            "into a community by their shared neighbor links, then reads the "
            "community's member names and descriptions as a summary. Every retrieved "
            "chunk records which path produced it. It is excluded from the default "
            "benchmark because a degraded (Neo4j-unreachable) result fails the "
            "benchmark run, unlike knowledge_graph and hybrid, which still carry that "
            "same risk in the default set today."
        ),
        "hybrid": (
            "Routes by intent and combines vector and graph passages with "
            "Reciprocal Rank Fusion. Report its added latency and graph dependency "
            "with its quality result."
        ),
        "raptor": (
            "Builds recursive summaries above the source chunks and retrieves "
            "across tree levels. It targets broad or cross-document questions."
        ),
        "pageindex": (
            "Builds a hierarchy from document structure and uses an LLM to traverse "
            "it. It gives a vector-free comparison for well-structured documents."
        ),
        "bm25": (
            "Ranks by lexical term matching without embeddings. It is the keyless "
            "baseline and often remains competitive when identifiers and exact "
            "terms dominate."
        ),
        "metadata_filtered": (
            "Applies an access filter, tags, owner, classification, and a document "
            "ID allow-list, inside retrieval. Scalar fields go into the Chroma "
            "`where` clause. Tags go into a Python check against an over-fetched "
            "candidate pool, then the result is cut to top_k. A chunk outside the "
            "filter never reaches the ranked list. An unknown classification level "
            "raises instead of allowing or denying everything by guess."
        ),
        "temporal": (
            "Prefers the newest eligible version of each document family and "
            "accepts an as-of date. Once a newer eligible version is present among "
            "the candidates, every chunk from an older version is dropped, so a "
            "superseded chunk cannot outrank its replacement. An unparseable as-of "
            "date raises."
        ),
        "rerank_vector": (
            "Retrieves a wider dense candidate set and rescores it with BGE, "
            "Cohere, or Voyage. Compare the quality lift with its latency and "
            "provider cost. BGE is the default. For Cohere or Voyage, install "
            "`cohere` or `voyageai`, set `KB_ARENA_RERANKER_BACKEND` to `cohere` or "
            "`voyage`, and set `KB_ARENA_COHERE_API_KEY` or "
            "`KB_ARENA_VOYAGE_API_KEY`. Run the strategy explicitly after "
            "installing the selected backend."
        ),
        "qiss": (
            "Reranks dense candidates with pure NumPy state-fidelity calculations. "
            "Its single-query score is a monotonic transform of cosine similarity, "
            "so a recall gain needs a separate multi-query operator."
        ),
        "sqr": (
            "Reduces embeddings to a power-of-two dimension, amplitude-encodes "
            "them, and runs a Qiskit Aer SWAP-test circuit."
        ),
        "hyde": (
            "Asks the LLM for a hypothetical answer to the question, then "
            "retrieves Naive Vector's index with that hypothetical answer instead "
            "of the question text."
        ),
        "multi_query": (
            "Asks the LLM for several sub-queries, retrieves Naive Vector's index "
            "once per sub-query, and fuses the ranked chunk lists with Reciprocal "
            "Rank Fusion."
        ),
        "late_interaction": (
            "Keeps one embedding per token instead of one pooled vector per "
            "passage, then reranks Naive Vector candidates by MaxSim: for every "
            "query token, the best cosine match among the passage tokens, averaged "
            "across query tokens."
        ),
        "splade": (
            "Expands a query and each indexed passage into a weighted set of "
            "vocabulary terms, then scores a query against a passage by the dot "
            "product of their term weights. It builds and reads its own "
            "term-weight index, so it needs no embedding provider."
        ),
        "agentic": (
            "Retrieves, then asks the LLM whether the gathered context already "
            "answers the question, and retrieves again with a refined query when "
            "it does not. A maximum iteration count and a maximum LLM-call count "
            "are set at construction time and enforced every round, so the loop "
            "always stops even when the judge keeps asking for another round."
        ),
    }


def _strategy_facts(spec) -> list[str]:
    """Short facts the catalog itself can state, so they cannot drift from it."""
    facts = [
        f"Architecture: {spec.architecture}",
        f"In the default benchmark: {'yes' if spec.default_benchmark else 'no'}",
    ]
    if spec.experimental:
        facts.append("Experimental: available for research, with no general performance claim")
    if spec.optional_extra:
        facts.append(f"Needs `pip install 'kb-arena[{spec.optional_extra}]'`")
    if not spec.api_supported:
        facts.append("Not reachable through the API")
    if not spec.needs_embeddings:
        facts.append("Calls no embedding provider")
    return facts


def render_strategy_catalog() -> str:
    from kb_arena.strategies.catalog import STRATEGY_CATALOG

    notes = _strategy_notes()
    lines = [
        GENERATED,
        "",
        "# Strategy catalog",
        "",
        "`kb_arena.strategies.catalog` is the source for built-in strategy names, "
        "default benchmark status, experiment labels, and optional dependencies. "
        "`GET /strategies` adds the loaded status for the current API process.",
        "",
        "Entries appear in the catalog's own order. The first entry is the dense "
        "baseline every other strategy compares against.",
        "",
    ]
    for spec in STRATEGY_CATALOG:
        note = notes.get(spec.name)
        if note is None:
            raise RuntimeError(
                f"docs/strategy-catalog.md has no note for {spec.name!r}. "
                "Add one to _strategy_notes() in scripts/generate_reference.py."
            )
        lines += [f"## {spec.label}", ""]
        lines += textwrap.wrap(note, width=88)
        lines.append("")
        for fact in _strategy_facts(spec):
            lines.append(f"- {fact}")
        lines.append("")
    lines += [
        "## Runtime states",
        "",
        "The following terms are distinct:",
        "",
        "- Registered: implemented in the installed package.",
        "- Default: included when a benchmark uses `all`.",
        "- Loaded: instantiated by the current API process.",
        "- Optional: needs an extra dependency group.",
        "- Experimental: available for research, with no general performance claim.",
        "",
        "The experimental entries answer research questions about operators and "
        "overhead. They do not define the main product category of KB Arena.",
        "",
        "Read `GET /strategies` for the loaded status of each strategy. Do not infer "
        "it from a fixed number.",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_cli() -> str:
    lines = [
        GENERATED,
        "",
        "# Command reference",
        "",
        "Every `kb-arena` command and its options.",
        "",
    ]
    for name, summary, flags in _cli_commands():
        lines += [f"## `kb-arena {name}`", ""]
        if summary:
            lines += [summary, ""]
        if flags:
            lines += ["| Option | What it does |", "|---|---|"]
            for flag, help_text in flags:
                lines.append(f"| `{flag}` | {help_text or '-'} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_api() -> str:
    lines = [
        GENERATED,
        "",
        "# HTTP reference",
        "",
        "Every route the server exposes, and what it asks of a caller.",
        "",
        "A route marked `token` needs `Authorization: Bearer <KB_ARENA_API_TOKEN>`.",
        "A route marked `token, unless local or a published demo` returns corpus",
        "content: it is open to a caller on this machine, open in a demo an",
        "operator published, and closed otherwise.",
        "",
        "| Route | Method | Auth |",
        "|---|---|---|",
    ]
    for path, method, gate in _api_routes():
        lines.append(f"| `{path}` | {method} | {gate} |")
    return "\n".join(lines).rstrip() + "\n"


def render_settings() -> str:
    lines = [
        GENERATED,
        "",
        "# Environment reference",
        "",
        "Every setting, read from `kb_arena/settings.py`. Each takes the",
        "`KB_ARENA_` prefix.",
        "",
        "| Variable | Default | What it does |",
        "|---|---|---|",
    ]
    for name, default, description in _settings_fields():
        lines.append(f"| `{name}` | `{default}` | {description or '-'} |")
    return "\n".join(lines).rstrip() + "\n"


TARGETS = {
    "docs/reference-cli.md": render_cli,
    "docs/reference-http.md": render_api,
    "docs/reference-environment.md": render_settings,
    "docs/strategy-catalog.md": render_strategy_catalog,
}


def main() -> int:
    for name, render in TARGETS.items():
        (ROOT / name).write_text(render())
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
