#!/usr/bin/env python3
"""Write the reference docs from the code, so they cannot drift from it.

A hand-written command list goes stale the first time somebody adds a command
and forgets the doc. This session added three commands and four flags that no
document mentioned, which is the same failure the strategy table had.

Run this after changing a command, a flag, a route or a setting:

    python3 scripts/generate_reference.py

`tests/test_reference_is_current.py` runs it in memory and fails when the files
on disk differ, so a stale reference cannot merge.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Read the checkout this script lives in, not whatever `kb-arena` an editable
# install points at. Without this the script described a different working
# copy: run from `scripts/`, `sys.path` holds that directory and not the repo,
# so `import kb_arena` resolved through the installed package instead.
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

GENERATED = "<!-- Generated by scripts/generate_reference.py. Do not edit by hand. -->"


def _cli_commands() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Every command, its first help line, and its long flags."""
    import typer.models

    from kb_arena.cli import app

    rows: list[tuple[str, str, list[tuple[str, str]]]] = []
    for info in app.registered_commands:
        name = info.name or (info.callback.__name__ if info.callback else "")
        name = name.replace("_", "-")
        doc = (info.callback.__doc__ or "").strip() if info.callback else ""
        summary = doc.splitlines()[0] if doc else ""
        flags: list[tuple[str, str]] = []
        callback = info.callback
        if callback is not None:
            import inspect

            for param in inspect.signature(callback).parameters.values():
                default = param.default
                if not isinstance(default, typer.models.OptionInfo):
                    continue
                names = [d for d in (default.param_decls or []) if str(d).startswith("--")]
                flag = names[0] if names else f"--{param.name.replace('_', '-')}"
                flags.append((str(flag), (default.help or "").strip()))
        rows.append((name, summary, sorted(flags)))
    return sorted(rows)


def _api_routes() -> list[tuple[str, str, str]]:
    """Every route the app serves, its method, and whether it needs a token.

    Read off the app, not off a regex over `api.py`. The app mounts a router
    with four routes under `/api/tools`, and a regex over one file missed every
    one of them. The reference then claimed to list every route and did not.
    """
    from kb_arena.chatbot.api import app
    from kb_arena.chatbot.auth import require_auth, require_read_auth

    # A set, not a list. A FastAPI version that copies a mounted router's
    # routes into `app.routes` as well as into the holder would otherwise print
    # every `/api/tools` row twice.
    found: set[tuple[str, str, str]] = set()
    for route in _walk_routes(app):
        path = getattr(route, "path", "")
        methods = getattr(route, "methods", None)
        dependant = getattr(route, "dependant", None)
        if not path or not methods or dependant is None:
            continue
        calls = {d.call for d in dependant.dependencies}
        if require_read_auth in calls:
            gate = "token, unless local or a published demo"
        elif require_auth in calls:
            gate = "token"
        else:
            gate = "open"
        for method in methods:
            if method in ("HEAD", "OPTIONS"):
                continue
            found.add((path, method.upper(), gate))

    # The app publishes its own route list. Checking the walk against it is what
    # makes a future mount impossible to miss in silence: a new router that this
    # walk does not reach fails the generator instead of shrinking the table.
    published = {
        (path, method.upper())
        for path, operations in app.openapi()["paths"].items()
        for method in operations
    }
    walked = {(path, method) for path, method, _ in found}
    missing = published - walked
    if missing:
        raise RuntimeError(
            f"the route walk missed {len(missing)} published route(s): {sorted(missing)}"
        )
    return sorted(found)


def _walk_routes(app):
    """Every route object, including the ones a mounted router holds.

    FastAPI wraps `include_router` in a lazy holder whose own `routes` list is
    empty until a request arrives. Following `original_router` reaches the real
    routes at generation time.
    """
    seen: list = []

    def _visit(holder) -> None:
        for route in getattr(holder, "routes", []) or []:
            if hasattr(route, "dependant"):
                seen.append(route)
            inner = getattr(route, "original_router", None)
            if inner is not None:
                _visit(inner)

    _visit(app)
    return seen


def _settings_fields() -> list[tuple[str, str, str]]:
    from kb_arena.settings import Settings

    rows = []
    for name, field in Settings.model_fields.items():
        default = field.default
        shown = "" if default is None else str(default)
        if isinstance(default, str) and default == "":
            shown = "(empty)"
        if "key" in name or "token" in name or "password" in name:
            shown = "(empty)" if not default else "(set)"
        rows.append((f"KB_ARENA_{name.upper()}", shown[:40], (field.description or "").strip()))
    return sorted(rows)


def render_cli() -> str:
    lines = [
        GENERATED,
        "",
        "# Command reference",
        "",
        "Every `kb-arena` command and its options.",
        "",
    ]
    for name, summary, flags in _cli_commands():
        lines += [f"## `kb-arena {name}`", ""]
        if summary:
            lines += [summary, ""]
        if flags:
            lines += ["| Option | What it does |", "|---|---|"]
            for flag, help_text in flags:
                lines.append(f"| `{flag}` | {help_text or '-'} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_api() -> str:
    lines = [
        GENERATED,
        "",
        "# HTTP reference",
        "",
        "Every route the server exposes, and what it asks of a caller.",
        "",
        "A route marked `token` needs `Authorization: Bearer <KB_ARENA_API_TOKEN>`.",
        "A route marked `token, unless local or a published demo` returns corpus",
        "content: it is open to a caller on this machine, open in a demo an",
        "operator published, and closed otherwise.",
        "",
        "| Route | Method | Auth |",
        "|---|---|---|",
    ]
    for path, method, gate in _api_routes():
        lines.append(f"| `{path}` | {method} | {gate} |")
    return "\n".join(lines).rstrip() + "\n"


def render_settings() -> str:
    lines = [
        GENERATED,
        "",
        "# Environment reference",
        "",
        "Every setting, read from `kb_arena/settings.py`. Each takes the",
        "`KB_ARENA_` prefix.",
        "",
        "| Variable | Default | What it does |",
        "|---|---|---|",
    ]
    for name, default, description in _settings_fields():
        lines.append(f"| `{name}` | `{default}` | {description or '-'} |")
    return "\n".join(lines).rstrip() + "\n"


TARGETS = {
    "docs/reference-cli.md": render_cli,
    "docs/reference-http.md": render_api,
    "docs/reference-environment.md": render_settings,
}


def main() -> int:
    for name, render in TARGETS.items():
        (ROOT / name).write_text(render())
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
